export const GET_PUBLISHER_PAGES = 'GET_PUBLISHER_PAGES';
export const SET_PUBLISHER_PAGES = 'SET_PUBLISHER_PAGES';
export const DEL_PUBLISHER_PAGE = 'DEL_PUBLISHER_PAGE';
export const DEL_PUBLISHER_PAGE_SUCCESS = 'DEL_PUBLISHER_PAGE_SUCCESS';
export const REFRESH_PUBLISHER_PAGE = 'REFRESH_PUBLISHER_PAGE';
export const REFRESH_PUBLISHER_PAGE_SUCCESS = 'REFRESH_PUBLISHER_PAGE_SUCCESS';
